GCP_PROJECT="kazadata-staging-prod-frkz"
BQ_DATASET="kzp_api_prod"
APP_PASSWORD="ADEOKZP2025"
[GOOGLE_CREDENTIALS]
type = "service_account"
project_id = "kazadata-staging-prod-frkz"
private_key_id = "4618d4901cbbe7c5dd36559ec75f514607f1b85c"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDrG6Gd8YzNISfJ
tpyUZVVzdKlKlpBQSzEumu6MS5d/OarLNw1pwNwvU2b+7eBF6wftlbiVHjLXIkJB
t2dnZJV/urT0lFbKNZSz6FidMUv29b0pRI58wF4Ar8/aOb0JGxyQOI4FS939uxsU
snvAwNwwlmG5xT9XY88iGFTIteJKfpLv59VOXvl04TNyY6Zyd4Qp3qfqQXvKqrWu
DCQYDZ3ShGw0HPf83/REZKQ8zmWhYNMcRPoE94IrVF9J+ZkIZqoYUWUCQPMuM96N
IhNVyE21HZDf0VLnf4ky97fhypjeY/278IVqiqD3KKlfK25palrd42qvocW0jveD
RhP5UFnFAgMBAAECggEAIQdC81wPdnLJsuPxR8SblkpljPmtYOZLTLuNtw5YhFI+
3OkJPJnQJOLf1YDn8JKVzMnrgiFZrZDdw3snLuZ5vRWm3bQoJCSWVRbXOhAGlrVL
g2xi4wIoQorwVX0mggy5vMYBJ5vSnhZGtefkDD5bwISjynP8E8QNAYJvCLpKhcHQ
3pwv774YFr4v/ihDq1QZunsvWbgDymrl7ahz90gwqP6Ui+ePdOyltBvYulfRN2wZ
9LPhYIr5kY9Vn9AFGmRVcEqTyN4D4ewXEpGGyS9J/gSsvtMgyCk9El2ahEoCPu0P
O7skeKBQUHFfUhpukcszRAmklzXdXhoAXOAv3FTxYQKBgQDt5lSEdvZiYBZ+VgIg
74xBsYWqKtQ0usJe4HeS3Mq0P+EkQX9ieZINjGxjvHN1IPz7Ae/k7gJ7l54TXURc
0XOuQnNKdg4WMHhKSveCyhL6ai8Zra/dqdnrJcnT7n9eJkWmOndD974RggcteDlq
x4MVOsj8sUNX9vBMV82aFu0YJQKBgQD8/uyekTZWCMr+LLPjBPOkN/5nq1O84HAh
5rL58PB76nuy0b1D+SDE4QJwuZ6qXnHAGR0LdQcjU72o85CjaTPmm/gAqX9e34zo
Tb6c9IF/YkwrnrclnHa5PE/dhC5/iHxgT+SCrhf97enbvC/l3DRVdXoFpJl1PgJd
7dS6kuA5IQKBgA24rz9ErUlXSXTX+R91MZ3IY3FBLyQrcXKPd9YcrgRfetjgfjxr
zqTBaK8H+5DR6kWAAxotMC94u0Faq8q+ufFfG887p+xXt1hxon0EsruGzFiqz+31
EgCiGVYD94yyoGnKDX76Fxhja46P1J/4CfN7hIQupTe5onqExfMRR3ORAoGAAYNk
1u33bTxQOoT57nmxG2JaWzRjI9YT1aATofsW9SbJ5p/qieWLlKHj6diyYkJ+W6/K
xK7GhCeUEtaiHtgaP17fdOGOqXqc1Sbh5P5xZ9mmqvwgDFGLREBgGesYfBrM46aW
r1FrQ1GQ/Id7odxXU8uIF1CMum7MhNNPWm5WeQECgYEA3f0UIN29QAe0r+NN46Pu
iJGEnD5ZAYJf9O9c2epj6KVUFabZkTNsg+0uEZXrpvyetOs59ey3cbAwwBI0aAWn
xryN6sLbpEIUb908ZWz0w/2jNiS+AoMMqDApsUFklmTolghvtA7ip8Ylf4WUoVp8
YNDZHmk+GknSIbMXv0eQZ4s=
-----END PRIVATE KEY-----"""
client_email = "gcf-load-kzp-data-bq@kazadata-staging-prod-frkz.iam.gserviceaccount.com"
client_id = "103545619951062043424"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/gcf-load-kzp-data-bq%40kazadata-staging-prod-frkz.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
